### ISSUE TITLE
Sign In using Facebook/Twitter/Google

### ISSUE THREAD

**Issue by gvsrini** [beeman/loopback-angular-admin#165]
I think this will be a good feature to add in.

**Comment by hdeshmukh** [comment]
Hi there,
I have tried to implement this and have gotten most things to work but the only issue is that whenever the final redirect to /auth/account is done I keep getting a 401 error.  Is there something missing that I need to add to make this function properly?  I believe the issue is in the following

app.get('/auth/account', ensureLoggedIn('/'), function (req, res, next) {
        console.log('Logged in', req.user)
        //Copy the cookie over for our AppAuth service that looks for accessToken cookie
        res.cookie('accessToken', req.signedCookies['access_token'], { signed: true });
        res.redirect('/#/app');
    });

On ensured LoggedIn on the root, there is no explicit app.get defined on that and so that is what prevents the final redirect from occurring. Any help would be greatly appreciated!

**Comment by hdeshmukh** [comment]
Ah....When the request to redirect to auth/account is made, the res.redirect ends up creating a request that is not authenticated....hence the 401 error.  Strange because loopback-component-passport does call req.login, so it should be storing that info somewhere so that the subsequent request is authenticated as well....

**Comment by hdeshmukh** [comment]
Might this be related to using express-session with memory db?

**Comment by sspansel** [comment]
I'm having what appears to be exactly this issue.

**Comment by hdeshmukh** [comment]
Figured out what the issue was.  Had to use express-session with Passport to enable the use of sessions with memorydb.  Added the following
    app.middleware('session', loopback.session({
        secret: app.get('cookieSecret'),
        saveUninitialized: true,
        resave: true
    }));
to enable session

**Comment by sspansel** [comment]
That fixed my problem; thanks!

**Comment by beeman** [comment]
Thanks for creating the issue and thanks a lot for the fix @hdeshmukh ! I've just added it to the master branch.

Can you please verify that it now works as expected?
