### ISSUE TITLE
How to run the project with production mode

### ISSUE THREAD

**Issue by amiashraf** [beeman/loopback-angular-admin#172]
Dear Team,
I am using the repository for my project and I was wondering to use the compressed js and css file (dist) for production mode.
May be the issue is irrelevant at this moment, but I was wondering to increase the performance of my project.
So far my project is taking so long and I am a bit frustrated.
Can you guys help me about?
Thanks in advance

**Comment by beeman** [comment]
Hi @amiashraf , can you give some more details of what performance issues you have?

I've not used the project as-is in production mode and as said in the readme, it is not ready for production. You probably need to change stuff in order to get it working properly.

If you have some specific questions me or someone else might be able to help.
