### ISSUE TITLE
Angular 2 conversion in the mix?

### ISSUE THREAD

**Issue by AvivLander** [beeman/loopback-angular-admin#178]
Just curious if there are any plans to convert this project to Angular 2? Has anyone started working on it?

**Comment by beeman** [comment]
Hi @AvivLander , the first priority for this project is modernizing it by using Babel and WebPack in order to enable usage of ES6 in the server side and front-end. I've started working on that [here](https://github.com/beeman/loopback-angular-admin/issues/179).

Once NG2 is final I will include it so it can be used next to NG1, and most likely update a few parts of the app. 

Currently the NG2 project is not stable enough to my liking to include, API's still change too frequently in order to keep up with it. Even though there is a release candidate out, I still have the feeling it will change quite a bit.

I hope this answers your question.

**Comment by beeman** [comment]
Follow up in this story https://github.com/beeman/loopback-angular-admin/issues/202
