### ISSUE TITLE
[HELP] blank screen 

### ISSUE THREAD

**Issue by wtlam** [beeman/loopback-angular-admin#191]
hi, 

thanks in advance for your help #

i have loopback-angular-admin setup on my linux box. 

i have mongo db installed and configured, 

there is no error when i start "npm start"

however, when i open http://{my linux ip}:3000 on my windows, i am not seeing anything, no error, just a blank screen. have anyone seems this before? 

$ MONGODB_URL="mongodb://localhost:27017/loopback-angular-admin" npm start

> loopback-angular-admin@0.1.1 start /prod6/alg/user/dev/web/loopback2
> node server/server.js

loopback deprecated loopback.cookieParser is deprecated. Use `require('cookie-parser');` instead. server/boot/passport.js:20:19
loopback deprecated loopback.session is deprecated. Use `require('express-session');` instead. server/boot/passport.js:21:37
Configuring passport
Web server listening at: http://localhost:3000
Browse your REST API at http://localhost:3000/explorer
Loading existing settings

**Comment by dawinjayesh** [comment]
i am facing the same issue. I am i doing anything wrong ?

**Comment by KratiChauhan** [comment]
try updating apiurl and siteurl in client-->js-->config.js file to either localhost or your linux ip.
That helped me solve the problem when my screen was not opening. Let me know if I not working as I am able to atleast make the screen work but am struggling to understand the tool and customize it to my need.
Hopefully once your issue is resolved you can help me further :)

**Comment by beeman** [comment]
This issue is created for the `v0.x` version of the project, which is no longer support nor maintained as of January 16th 2017. I'm therefore closing this issue.

All development effort will be put in the new version of the project that is named Colmena CMS.
