### ISSUE TITLE
left menu should be scrollable for smaller screen factors.

### ISSUE THREAD

**Issue by paulvanbladel** [beeman/loopback-angular-admin#37]
On a 8 inch tablet, the last  menu items are not visible.
the scrolling on the main region works like a charm.
cheers

**Comment by beeman** [comment]
Temporary fix is that you select the 'scrolling' layout in Dashboard -> Theme. 

I'm also not happy with how this works so I will have to dive into enhancing it. Issue is related to #40 .

**Comment by beeman** [comment]
As I was not completely happy with the AdminLTE theme that I implemented, I've implemented [rdash-angular](https://github.com/rdash/rdash-angular) in a [temporary branch](https://github.com/beeman/loopback-angular-admin/tree/feature/improved-layout).

This template has much less bloated than AdminLTE and it supports the resizing on smaller devices very well.

Please let me know what you think of it!

**Comment by beeman** [comment]
Of course @movibe @macbroadcast @bmcintyre @rhalff @rborn (and everybody else) are more then welcome to discuss this too! :)

**Comment by beeman** [comment]
I have a demo online on Heroku: http://loopback-rdash.herokuapp.com/

**Comment by paulvanbladel** [comment]
Very nice !
For those not knowing username password: admin@admin.com / admin.
The left menu scroll bar is doing the job.
Maybe the windows mobile alike tiles in the AdminLTE were a bit more sexy, but that's probably just a matter of taste.

**Comment by movibe** [comment]
It was much better.
I would like you to take a look also in a version with the Gulp instead of Grunt, where I added the Less version of the original theme Admin LTE and some improvements.

**Comment by beeman** [comment]
@paulvanbladel I agree that the tiles of AdminLTE looked better, i'll merge them along with some other stuff.

**Comment by beeman** [comment]
@movibe i've looked at your Gulp version, which does look very nice! I am thinking about moving to gulp instead of Grunt anyway.

The thing that I don't like about AdminLTE is that it is too bloated, there are simply too many options that won't be implemented in this base project. Next to that the interface is buggy (especially on small screens) and very picky about how it's implemented, I had to change the base AdminLTE to get it to work in this project. 

What I like about RDash is that is is clean and simple, and provided as a bower module.

Could you tell what you like more about AdminLTE? If it is just the way it looks we could implement some sort of theming system where we mimic the looks of AdminLTE.

**Comment by movibe** [comment]
I'm glad you liked my version, just could not solve the dependency error and since you would like to ask you if you could help me solve?

As for AminLTE, imagine that you have used it to be free, but what I wanted to add was more the advantage of compiling Less version and give the freedom to easily change the theme to use in other projects without the need to have large changes in CSS, and added a task to Gulp, but if I like the layout of it, I confess that I find very simple and swollen like you said.

But as you are the leader of the project, you have the greatest word decision.

I confess that the version you did was much prettier and better for tablets, but it will run away from the base of AdminLTE and become a unique template, this is not bad, it may be the best way, but depends on its future plans for the project and I will collaborate as planned.

And forgive my English, I speak Brazilian Portuguese and use google translator rs

**Comment by beeman** [comment]
@movibe Your English is still better than my Portuguese :)

I guess I'll take this route for now and implement some of the other stuff that AdminLTE offers.

If you can than rebase the gulp version to the new layout I'll check and implement it too!

**Comment by lennybr** [comment]
I definitely second the switch to rdash-angular, a much lighter framework to expand on!

**Comment by beeman** [comment]
Closing in favor of work on project based on Angular 2+ / TypeScript. Follow here https://github.com/beeman/loopback-angular-admin/issues/202
