### ISSUE TITLE
Layout from a fresh install appears broken

### ISSUE THREAD

**Issue by asgeirbirkis** [beeman/loopback-angular-admin#84]
Doing a fresh clone (currently at commit 699d60640a), then `npm install`, followed by `nodemon` and `grunt serve` gives me a layout of a site that appears broken. See attached screenshots. What confuses me even more is that I've previously downloaded the repo (about two months ago) and everything looked nice like in the screenshots when I ran the same command. Am I doing something silly or is something broken?

![screen shot 2015-06-16 at 21 29 01](https://cloud.githubusercontent.com/assets/3543429/8193730/cdcf3956-146e-11e5-9947-030168314421.png)
![screen shot 2015-06-16 at 21 29 20](https://cloud.githubusercontent.com/assets/3543429/8193731/cdd0138a-146e-11e5-8815-4d60fccebd1d.png)

**Comment by stvnmcdonald** [comment]
This is happening for me as well, even with the "Deploy to Heroku" option.

**Comment by beeman** [comment]
Thanks for creating this issue, I'll check it tomorrow as I don't have high-speed internet at this moment.

I don't think it's your fault, especially when more people have this problem. It's probably an issue with one of the bower/npm packages.

**Comment by beeman** [comment]
The problem was caused by the fact that the packages in bower.json were not fixed to a certain version but rather always updated to the latest version thanks to the caret notation (^).

This caused bootstrap to upgrade to version 3.5.3 which removes the CSS file to be included by default https://github.com/twbs/bootstrap/commit/38861984d9035333e2b366d307a5b874df8b8759

It should work again now, I'm deploying it to Heroku as we speak :)

**Comment by asgeirbirkis** [comment]
Thanks @beeman for looking into this, looking forward to keep experimenting with the code over the weekend!
