### ISSUE TITLE
User access

### ISSUE THREAD

**Issue by wesleymilan** [beeman/loopback-angular-admin#90]
Hi Beeman,

I'm trying to do the user having no access to other users profiles, specially admin's profile even him not having permissions to change, at this time he can list all users, how can I restrict his listing access to himself only?

Thank you for your help

**Comment by beeman** [comment]
Hi @wesleymilan, this is probably best done using the ACL. 

Since the ACL is not yet support it is best to look elsewhere for your solution.

For general questions about LoopBack I recommend you to go to one of these gitter rooms and ask there:

https://gitter.im/strongloop/loopback
https://gitter.im/loopbackers/loopbackers.github.io
