### ISSUE TITLE
Grunt build problem

### ISSUE THREAD

**Issue by josx** [beeman/loopback-angular-admin#98]
On ```grunt build ``` runs server.js but I dont understand why.
There is a problem between running:  "loopback_sdk_angular:production" and after "includeSource:dist" tasks.
So Everytime I run ```grunt serve``` is booting loopback app run twice. 

To test it you can add a little task on Gruntfile.js

```js
grunt.registerTask('buildproblem', [
    'loopback_sdk_angular:production',
    'includeSource:dist',
]);
```
and then run
```
grunt buildproblem
```

**Comment by beeman** [comment]
@josx the server is started by `loopback_sdk_angular` so that it can generate the file `lbServices` that is used by the front end. 

This is not an issue but the way the project is designed. 

If you don't like the fact that this file is generated each time the server starts you can generate it and store it under version control, but for this project I feel that it should generate each run to easily accommodate changes in the models.
